services:
  db:
    image: postgres:16
    container_name: dundermifflin-fei-db
    environment:
      POSTGRES_USER: setpoint
      POSTGRES_PASSWORD: setpoint
      POSTGRES_DB: setpoint
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: